-- =========================================================================
-- SISTEMA FINANCEIRO RAPHAEL NILSEN
-- Script de Criação das Tabelas Individuais no Supabase (PostgreSQL)
-- Copie e cole este script no SQL Editor do Supabase e clique em RUN
-- =========================================================================

-- 1. Contas Bancárias e Carteira
CREATE TABLE IF NOT EXISTS public.contas_bancarias (
    id TEXT PRIMARY KEY,
    user_email TEXT NOT NULL,
    nome TEXT NOT NULL,
    tipo TEXT,
    saldo NUMERIC(12,2) DEFAULT 0.00,
    cor TEXT,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Rendimentos / Receitas (Todos os meses e anos)
CREATE TABLE IF NOT EXISTS public.receitas (
    id TEXT PRIMARY KEY,
    user_email TEXT NOT NULL,
    ano INT NOT NULL,
    mes INT NOT NULL,
    descricao TEXT NOT NULL,
    valor NUMERIC(12,2) NOT NULL,
    data TEXT,
    status TEXT DEFAULT 'Pendente',
    banco TEXT,
    tipo TEXT DEFAULT 'mensal',
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Despesas Fixas (Aluguel, Luz, Internet, etc.)
CREATE TABLE IF NOT EXISTS public.despesas_fixas (
    id TEXT PRIMARY KEY,
    user_email TEXT NOT NULL,
    ano INT NOT NULL,
    mes INT NOT NULL,
    descricao TEXT NOT NULL,
    valor_previsto NUMERIC(12,2) DEFAULT 0.00,
    valor_pago NUMERIC(12,2) DEFAULT 0.00,
    data_vencimento TEXT,
    status TEXT DEFAULT 'Pendente',
    banco TEXT,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Despesas Variáveis (Mercado, Lazer, etc.)
CREATE TABLE IF NOT EXISTS public.despesas_variaveis (
    id TEXT PRIMARY KEY,
    user_email TEXT NOT NULL,
    ano INT NOT NULL,
    mes INT NOT NULL,
    descricao TEXT NOT NULL,
    valor NUMERIC(12,2) NOT NULL,
    data TEXT,
    categoria TEXT,
    banco TEXT,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Compras no Cartão de Crédito (Master, Nubank, etc.)
CREATE TABLE IF NOT EXISTS public.compras_cartao (
    id TEXT PRIMARY KEY,
    user_email TEXT NOT NULL,
    descricao TEXT NOT NULL,
    estabelecimento TEXT,
    cartao TEXT NOT NULL,
    data_compra TEXT NOT NULL,
    valor_total NUMERIC(12,2) NOT NULL,
    parcelas INT NOT NULL,
    ano_inicio INT NOT NULL,
    mes_inicio INT NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Investimentos em Bolsa (Ações e FIIs)
CREATE TABLE IF NOT EXISTS public.investimentos_bolsa (
    id TEXT PRIMARY KEY,
    user_email TEXT NOT NULL,
    ticker TEXT NOT NULL,
    tipo TEXT DEFAULT 'Ação',
    quantidade NUMERIC(12,4) DEFAULT 0,
    preco_medio NUMERIC(12,2) DEFAULT 0,
    total_aplicado NUMERIC(12,2) DEFAULT 0,
    data_compra TEXT,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. Investimentos Nubank (Caixinhas e Renda Fixa)
CREATE TABLE IF NOT EXISTS public.investimentos_caixinhas (
    id TEXT PRIMARY KEY,
    user_email TEXT NOT NULL,
    nome TEXT NOT NULL,
    valor NUMERIC(12,2) DEFAULT 0.00,
    status TEXT DEFAULT 'Ativa',
    data_aplicacao TEXT,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 8. Troco Jotur (Base R$ 200,00 e Histórico de Conferências)
CREATE TABLE IF NOT EXISTS public.troco_jotur (
    id TEXT PRIMARY KEY,
    user_email TEXT NOT NULL,
    data_hora TEXT NOT NULL,
    troco_base NUMERIC(12,2) DEFAULT 200.00,
    total_contado NUMERIC(12,2) NOT NULL,
    resultado TEXT NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 9. Cofre de Senhas Protegido
CREATE TABLE IF NOT EXISTS public.cofre_senhas (
    id TEXT PRIMARY KEY,
    user_email TEXT NOT NULL,
    servico TEXT NOT NULL,
    categoria TEXT,
    usuario TEXT,
    senha TEXT NOT NULL,
    url TEXT,
    notas TEXT,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 10. Sonhos e Metas de Compras
CREATE TABLE IF NOT EXISTS public.sonhos_metas (
    id TEXT PRIMARY KEY,
    user_email TEXT NOT NULL,
    titulo TEXT NOT NULL,
    valor_alvo NUMERIC(12,2) NOT NULL,
    valor_atual NUMERIC(12,2) DEFAULT 0.00,
    data_alvo TEXT,
    categoria TEXT,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 11. Bombeiro Comunitário (Ressarcimentos)
CREATE TABLE IF NOT EXISTS public.bombeiro_ressarcimento (
    id TEXT PRIMARY KEY,
    user_email TEXT NOT NULL,
    mes_referencia TEXT NOT NULL,
    data_solicitada TEXT,
    data_pagamento TEXT,
    valor NUMERIC(12,2) NOT NULL,
    status TEXT DEFAULT 'Pendente',
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 12. Cofre Geral Consolidado (JSONB de Segurança)
CREATE TABLE IF NOT EXISTS public.financial_vault (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email TEXT UNIQUE NOT NULL,
    data_json JSONB NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- =========================================================================
-- PERMISSÕES DE ACESSO (Permitir leitura e gravação da aplicação web)
-- =========================================================================
ALTER TABLE public.contas_bancarias DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.receitas DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.despesas_fixas DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.despesas_variaveis DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.compras_cartao DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.investimentos_bolsa DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.investimentos_caixinhas DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.troco_jotur DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.cofre_senhas DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.sonhos_metas DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.bombeiro_ressarcimento DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.financial_vault DISABLE ROW LEVEL SECURITY;
