-- =========================================================================
-- SISTEMA FINANCEIRO RAPHAEL NILSEN
-- Script de Criação das Tabelas Individuais no Supabase (PostgreSQL)
-- Copie e cole este script no SQL Editor do Supabase e clique em RUN
-- =========================================================================

-- 1. Contas Bancárias e Carteira
CREATE TABLE IF NOT EXISTS public.contas_bancarias (
    id TEXT PRIMARY KEY,
    user_email TEXT NOT NULL,
    nome TEXT NOT NULL,
    tipo TEXT,
    saldo NUMERIC(12,2) DEFAULT 0.00,
    cor TEXT,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Rendimentos / Receitas (Todos os meses e anos)
CREATE TABLE IF NOT EXISTS public.receitas (
    id TEXT PRIMARY KEY,
    user_email TEXT NOT NULL,
    ano INT NOT NULL,
    mes INT NOT NULL,
    descricao TEXT NOT NULL,
    valor NUMERIC(12,2) NOT NULL,
    data TEXT,
    status TEXT DEFAULT 'Pendente',
    banco TEXT,
    tipo TEXT DEFAULT 'mensal',
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Despesas Fixas (Aluguel, Luz, Internet, etc.)
CREATE TABLE IF NOT EXISTS public.despesas_fixas (
    id TEXT PRIMARY KEY,
    user_email TEXT NOT NULL,
    ano INT NOT NULL,
    mes INT NOT NULL,
    descricao TEXT NOT NULL,
    valor_previsto NUMERIC(12,2) DEFAULT 0.00,
    valor_pago NUMERIC(12,2) DEFAULT 0.00,
    data_vencimento TEXT,
    status TEXT DEFAULT 'Pendente',
    banco TEXT,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Despesas Variáveis (Mercado, Lazer, etc.)
CREATE TABLE IF NOT EXISTS public.despesas_variaveis (
    id TEXT PRIMARY KEY,
    user_email TEXT NOT NULL,
    ano INT NOT NULL,
    mes INT NOT NULL,
    descricao TEXT NOT NULL,
    valor NUMERIC(12,2) NOT NULL,
    data TEXT,
    categoria TEXT,
    banco TEXT,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Compras no Cartão de Crédito (Master, Nubank, etc.)
CREATE TABLE IF NOT EXISTS public.compras_cartao (
    id TEXT PRIMARY KEY,
    user_email TEXT NOT NULL,
    descricao TEXT NOT NULL,
    estabelecimento TEXT,
    cartao TEXT NOT NULL,
    data_compra TEXT NOT NULL,
    valor_total NUMERIC(12,2) NOT NULL,
    parcelas INT NOT NULL,
    ano_inicio INT NOT NULL,
    mes_inicio INT NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Investimentos em Bolsa (Ações e FIIs)
CREATE TABLE IF NOT EXISTS public.investimentos_bolsa (
    id TEXT PRIMARY KEY,
    user_email TEXT NOT NULL,
    ticker TEXT NOT NULL,
    tipo TEXT DEFAULT 'Ação',
    quantidade NUMERIC(12,4) DEFAULT 0,
    preco_medio NUMERIC(12,2) DEFAULT 0,
    total_aplicado NUMERIC(12,2) DEFAULT 0,
    data_compra TEXT,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. Investimentos Nubank (Caixinhas e Renda Fixa)
CREATE TABLE IF NOT EXISTS public.investimentos_caixinhas (
    id TEXT PRIMARY KEY,
    user_email TEXT NOT NULL,
    nome TEXT NOT NULL,
    valor NUMERIC(12,2) DEFAULT 0.00,
    status TEXT DEFAULT 'Ativa',
    data_aplicacao TEXT,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 8. Troco Jotur (Base R$ 200,00 e Histórico de Conferências)
CREATE TABLE IF NOT EXISTS public.troco_jotur (
    id TEXT PRIMARY KEY,
    user_email TEXT NOT NULL,
    data_hora TEXT NOT NULL,
    troco_base NUMERIC(12,2) DEFAULT 200.00,
    total_contado NUMERIC(12,2) NOT NULL,
    resultado TEXT NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 9. Cofre de Senhas Protegido
CREATE TABLE IF NOT EXISTS public.cofre_senhas (
    id TEXT PRIMARY KEY,
    user_email TEXT NOT NULL,
    servico TEXT NOT NULL,
    categoria TEXT,
    usuario TEXT,
    senha TEXT NOT NULL,
    url TEXT,
    notas TEXT,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 10. Sonhos e Metas de Compras
CREATE TABLE IF NOT EXISTS public.sonhos_metas (
    id TEXT PRIMARY KEY,
    user_email TEXT NOT NULL,
    titulo TEXT NOT NULL,
    valor_alvo NUMERIC(12,2) NOT NULL,
    valor_atual NUMERIC(12,2) DEFAULT 0.00,
    data_alvo TEXT,
    categoria TEXT,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 11. Bombeiro Comunitário (Ressarcimentos)
CREATE TABLE IF NOT EXISTS public.bombeiro_ressarcimento (
    id TEXT PRIMARY KEY,
    user_email TEXT NOT NULL,
    mes_referencia TEXT NOT NULL,
    data_solicitada TEXT,
    data_pagamento TEXT,
    valor NUMERIC(12,2) NOT NULL,
    status TEXT DEFAULT 'Pendente',
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 12. Cofre Geral Consolidado (JSONB de Segurança)
CREATE TABLE IF NOT EXISTS public.financial_vault (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email TEXT UNIQUE NOT NULL,
    data_json JSONB NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- =========================================================================
-- PERMISSÕES DE ACESSO (Permitir leitura e gravação da aplicação web)
-- =========================================================================
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;

ALTER TABLE public.contas_bancarias ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permissao_Total_Contas" ON public.contas_bancarias;
CREATE POLICY "Permissao_Total_Contas" ON public.contas_bancarias FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

ALTER TABLE public.receitas ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permissao_Total_Receitas" ON public.receitas;
CREATE POLICY "Permissao_Total_Receitas" ON public.receitas FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

ALTER TABLE public.despesas_fixas ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permissao_Total_DespFixas" ON public.despesas_fixas;
CREATE POLICY "Permissao_Total_DespFixas" ON public.despesas_fixas FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

ALTER TABLE public.despesas_variaveis ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permissao_Total_DespVar" ON public.despesas_variaveis;
CREATE POLICY "Permissao_Total_DespVar" ON public.despesas_variaveis FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

ALTER TABLE public.compras_cartao ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permissao_Total_Cartao" ON public.compras_cartao;
CREATE POLICY "Permissao_Total_Cartao" ON public.compras_cartao FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

ALTER TABLE public.investimentos_bolsa ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permissao_Total_Bolsa" ON public.investimentos_bolsa;
CREATE POLICY "Permissao_Total_Bolsa" ON public.investimentos_bolsa FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

ALTER TABLE public.investimentos_caixinhas ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permissao_Total_Caixinhas" ON public.investimentos_caixinhas;
CREATE POLICY "Permissao_Total_Caixinhas" ON public.investimentos_caixinhas FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

ALTER TABLE public.troco_jotur ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permissao_Total_Jotur" ON public.troco_jotur;
CREATE POLICY "Permissao_Total_Jotur" ON public.troco_jotur FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

ALTER TABLE public.cofre_senhas ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permissao_Total_Senhas" ON public.cofre_senhas;
CREATE POLICY "Permissao_Total_Senhas" ON public.cofre_senhas FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

ALTER TABLE public.sonhos_metas ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permissao_Total_Sonhos" ON public.sonhos_metas;
CREATE POLICY "Permissao_Total_Sonhos" ON public.sonhos_metas FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

ALTER TABLE public.bombeiro_ressarcimento ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permissao_Total_Bombeiro" ON public.bombeiro_ressarcimento;
CREATE POLICY "Permissao_Total_Bombeiro" ON public.bombeiro_ressarcimento FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

ALTER TABLE public.financial_vault ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permissao_Total_Vault" ON public.financial_vault;
CREATE POLICY "Permissao_Total_Vault" ON public.financial_vault FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

